apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krb-operator
rules:
- apiGroups:
    - ''
    - authorization.k8s.io
    - extensions
  resources:
    - pods
    - services
    - configmaps
    - secrets
    - pods/exec
    - deploymentconfigs
  verbs:
    - get
    - watch
    - list
    - create
    - update
    - delete
- apiGroups:
    - ''
  resources:
    - namespaces
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - watch
    - list
    - create
- apiGroups:
    - krb-operator.novakov-alexey.github.io
  resources:
    - krbservers
    - krbservers/status
    - principalss
    - principalss/status
  verbs:
    - watch
    - list
    - update
- apiGroups:
    - apps.openshift.io
  resources:
    - deploymentconfigs
  verbs:
    - get
    - create
    - list
    - delete
- apiGroups:
    - ''
    - apps
    - extensions
  resources:
    - deployments
  verbs:
    - get
    - create
    - list
    - delete