{{ if and .Values.security.enabled (eq .Values.security.authentication "kerberos") }}
apiVersion: krb-operator.novakov-alexey.github.io/v1
kind: Principals
metadata:
  name: ozone-service-principals
  labels:
    krb-operator.novakov-alexey.github.io/server: {{ .Values.security.kerberos.server }}
spec:
  list:
    - name: scm
      keytab: {{ base .Values.scm.security.kerberos.keytab.path }}
      password:
        type: static
        value: scm
      secret:
        type: KeytabAndPassword
        name: scm-keytab
    - name: om
      keytab: {{ base .Values.om.security.kerberos.keytab.path }}
      password:
        type: static
        value: om
      secret:
        type: KeytabAndPassword
        name: om-keytab
    - name: datanode
      keytab: {{ base .Values.datanode.security.kerberos.keytab.path }}
      password:
        type: static
        value: datanode
      secret:
        type: KeytabAndPassword
        name: datanode-keytab
{{ end }}