image:
  name: apache/ozone
  version: 1.1.0

security:
  enabled: true
  authentication: kerberos

  # used when authentication is kerberos
  kerberos:
    server: krb-server
    realm: EXAMPLE.COM

om:
  replicas: 1
  volume:
    storage: 2Gi
  security:
    kerberos:
      keytab:
        path: /etc/security/keytabs/om.keytab

scm:
  replicas: 1
  volume:
    storage: 2Gi
  security:
    kerberos:
      keytab:
        path: /etc/security/keytabs/scm.keytab
  container:
    size: 1GB

  # hdds
  safemode:
    min:
      datanode: 1 # must be less than or equal to datanode replicas.

s3g:
  replicas: 1

datanode:
  replicas: 1
  volume:
    storage: 2Gi
  pipeline:
    limit: 1 # must be less than or equal to datanode replicas.
# datanode uses scm keytab
#  security:
#    kerberos:
#      keytab:
#        path: /etc/security/keytabs/datanode.keytab
